name: Feature Request
description: Suggest a new feature or enhancement
title: "[FEATURE]: "
labels: ["feature-request", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Suggest a new feature or enhancement for VRC Event Creator.

        Please describe the problem you're trying to solve, not just the solution you want.

  - type: checkboxes
    id: prerequisites
    attributes:
      label: Prerequisites
      options:
        - label: I have searched existing issues and feature requests
          required: true

  - type: dropdown
    id: category
    attributes:
      label: Feature Category
      description: What area of the app does this feature relate to?
      options:
        - Event Management
        - Automation
        - UI/UX
        - Gallery
        - Profiles/Templates
        - Settings/Configuration
        - Other
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve? What pain point are you experiencing?
      placeholder: |
        Currently, I have to manually... which takes a lot of time when...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe your ideal solution to this problem
      placeholder: |
        Add a button that allows me to...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered any alternative solutions or workarounds?
      placeholder: |
        I've tried... but it doesn't work well because...

  - type: textarea
    id: additional_context
    attributes:
      label: Additional Context
      description: Add any other context, use cases, or examples
      placeholder: |
        This would be especially useful when...

  - type: textarea
    id: mockups
    attributes:
      label: Mockups/Examples
      description: If you have mockups, wireframes, or examples from other apps, share them here
      placeholder: Drag and drop images here
